### ISSUE TITLE
第8回課題フィードバック

### ISSUE THREAD

**Issue by YoshioKimura** [junko113/08#1]
チューターの木村です。
コメントが遅くなりすみません！

cssをbootstrap頼りではなくstyle.cssに書いてカスタマイズしているのは良いですね！(style.cssの中にabout
meとあるので、参考にしたのは自己紹介サイト等ですかね。。？)

動作の方ですが、sqlファイルをインポートしてentry.phpからデータを登録する際に、
Undefined index: name in ***** insert.php on line 5
というエラーメッセージが表示されました。
調べてみると、insert.phpにある

$name   = $_POST["name"];
$lid  = $_POST["lid"];
$lpw  = $_POST["lpw"];

の三行の$_POST[" *** "]; の部分がentry.phpのformタグの中にあるname属性と値が違っているようです。

ユーザー登録の部分の登録が問題無く出来ていたのを拝見し、おそらく出来るかと思いますので、お時間ある時に一度見直して見てください！

**Comment by junko113** [comment]
木村さん
コメント有難うございます！(返信が大変遅くなり、大変申し訳ありません。。)

bootstrapをうまく使いこなせなかったという裏事情があります。。
CSSについて、やっと最近苦手意識をなくせてきたので、今後もCSSの基礎知識を抑えつつ勉強していきたい所存です。

データ登録部分についてご確認・ご指摘頂き有難うございました。
時間がある際に、再度見直しさせて頂きます。
よろしくお願い致します。
